### ISSUE TITLE
missing libraries

### ISSUE THREAD

**Issue by kilianbreathnach** [jltinker/clustering_code#1]
The makefile should include a flag for nrutil (and ideally have the associated code in the repo...) in order to have references to vector, dmatrix etc. There is also no libcutil included.

**Comment by jltinker** [comment]
Ack! Totally forgot about that. I'll check in the cutil library code and the nrutil.h file.

**Comment by jltinker** [comment]
nrutil.c is in the cutil library. i'll check that into a separate repo.

**Comment by jltinker** [comment]
Done. check out "lib" repo.
